# Generated by Django 4.2.1 on 2023-06-05 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50, validators=[django.core.validators.validate_integer])),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
