# Generated by Django 4.2.1 on 2023-06-05 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_contacto_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.validate_integer]),
        ),
    ]
